### PR TITLE
Fix types

### PR DESCRIPTION
**Pull request by tibotiber**
Hi, really handy library, thank you. I'm a typescript user and realized that the types defined are wrong as the 2 decimal coordinates are numbers, not string. Here is a proposed quick fix.

I'm not familiar with this build setup for types, but that's the only place I found anything in the form of type declarations, so hopefully it works.

Happy to iterate if needed.

### CODE REVIEW

**Comment by ianengelbrecht** [comment]
Thank you very much, greatly appreciated (and not sure how that slipped through the cracks TBH!)

**Comment by ianengelbrecht** [comment]
Merged and published

**Comment by tibotiber** [comment]
Lovely, thanks for the quick merge. And these cracks are always there, just for the community to feel involved ;)

**Comment by tibotiber** [comment]
PS: could you ping here once published to npm?

**Comment by ianengelbrecht** [comment]
Yes it's up on npm, please check the version bump there, should be 1.7.4

**Comment by tibotiber** [comment]
Yep, I see it now 🙌

**Pull request merged**
